# See: https://github.com/DavidAnson/vscode-markdownlint#configure

line-length: false
no-hard-tabs:
  spaces_per_tab: 2
no-multiple-blanks:
  maximum: 2
ul-indent:
  indent: 2
heading-increment: false
no-inline-html:
  allowed_elements:
    - a
