
site_name: 121 Platform User Manual

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - toc:
        toc_depth : "1-1"
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search

theme:
    name: material
    language: en
    palette:
      primary: custom
    logo: assets/img/121Logo.svg

extra:
  generator: false
#   alternate:
#     - name: English
#       link: /
#       lang: en
#     - name: Nederlands
#       link: /nl/
#       lang: nl

nav:
    - 'Home': 'index.md'
    - 'Support': 'general/support-contact.md'
    - 'General':
      - 'Log In': 'general/logging-in.md'
      - 'Change current password': 'general/change-current-password.md'
      - 'Reset password': 'general/reset-password.md'
      - 'Change Language': 'general/change-language.md'
      - 'Registration': 'registration/registration.md'
    - 'Running Your Program':
      - 'Program Design': 'design/design.md'
      - 'Registration': 'registration/registration.md'
      - 'Inclusion': 'inclusion/inclusion.md'
      - 'Payment': 'payment/payment.md'
      - 'Evaluation': 'evaluation/evaluation.md'
    - 'Users and Roles' :
      - 'Users Overview': 'users/users-roles-page.md'
      - 'Add Users': 'users/add-users.md'
      - 'Roles and permissions': 'users/description-roles.md'
    - 'Program Team': 
      - 'Team page': 'team/team-page.md'
      - 'Add team members': 'team/add-team-members.md'
      - 'Change team members roles': 'team/change-team-roles-program.md'
      - 'Remove team members': 'team/remove-team-members-program.md'
    - 'Program Design':
      - 'Program Design': 'design/design.md'
      - 'Read & Change Program Design': 'design/read-change-design-details.md'
    - 'Registration':
      - 'Registration Overview': 'registration/registration.md'
      - 'Import excel file': 'registration/registration-import-list.md'
      - 'Automatic import with KOBO': 'registration/registration-automatic-import-kobo.md'
      - 'Deduplication': 'registration/registration-deduplication.md'
      - 'Validate registration': 'registration/registration-validate-pa.md'
      - 'Reject registration': 'registration/registration-validate-pa.md'
      - 'Empty Registration List': 'registration/registration-list-empty.md'
    - 'Inclusion':
      - 'Inclusion Overview': 'inclusion/inclusion.md'
    - 'Payment':
      - 'Payment Overview': 'payment/payment.md'
    - 'Evaluation':
      - 'Evaluation Overview': 'evluation/evaluatio.md'

      

      
