
site_name: 121 Platform User Manual

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - toc:
        toc_depth : "1-1"
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

theme:
    name: material
    language: en
    palette:
      primary: custom
    logo: assets/img/121Logo.svg

extra:
  generator: false
#   alternate:
#     - name: English
#       link: /
#       lang: en
#     - name: Nederlands
#       link: /nl/
#       lang: nl

nav:
    - 'Home': 'index.md'
    - 'General':
      - 'Log In': 'general/logging-in.md'
      - 'Change current password': 'general/change-current-password.md'
      - 'Reset password': 'general/reset-password.md'
      - 'Add Team Members': 'general/add-team-members.md'
      - 'Add Users': 'general/add-users.md'
      - 'Change Language': 'general/change-language.md'
      - 'Registration': 'general/registration.md'
    - 'Running Your Program':
      - 'Program Design': 'ProgramOverview/design.md'
      - 'Registration': 'ProgramOverview/registration.md'
      - 'Inclusion': 'ProgramOverview/inclusion.md'
      - 'Payment': 'ProgramOverview/payment.md'
      - 'Evaluation': 'ProgramOverview/evaluation.md'
