# See: https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration
# See: https://www.mkdocs.org/user-guide/configuration/

site_name: 121 Platform User Manual
site_url: https://manual.121.global/
docs_dir: '../../docs/nlrc/nl'
site_dir: '../../www/nl'

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - toc:
      toc_depth: "1-1"
      permalink: true
      permalink_title: Specific link to this section
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - privacy:
      assets: false
  - search
  - glightbox

theme:
  name: material
  custom_dir: ../../overrides
  language: nl
  palette:
    primary: custom
  logo: assets/img/121Logo.svg
  favicon: assets/img/favicon.ico
  features:
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky

extra:
  generator: false
  alternate:
  - name: English
    link: /en/
    lang: en
  analytics:
    provider: custom
    matomoUrl: "https://510global.matomo.cloud/"  # Your Matomo server URL (with trailing slash)
    siteId: "12"  # Your site ID from Matomo
    feedback:
      title: Was deze pagina nuttig?
      ratings:
        - icon: material/thumb-up-outline
          name: Ja, deze pagina was nuttig
          data: 1
          note: >-
            Bedankt voor je feedback!
        - icon: material/thumb-down-outline
          name: Nee, deze pagina kan verbeterd worden
          data: 0
          note: >-
            Bedankt voor je feedback! Help ons deze pagina te verbeteren,
            <a href="mailto:support@121.global?subject=Feedback%20on%20121-Manual:%20{url}" rel="noopener">laat ons weten wat je ervan vindt</a>.

extra_javascript:
  - assets/javascripts/feedback.js

nav:
  - "🇳🇱 NLRC":
    - "Home": "index.md"
    - "Inloggen via 2FA (2 Factor Authentication)": "log-in-2fa.md"
    - "Taal aanpassen": "change-language.md"
    - "Hulpvragers Tabel": "registrations-table.md"
    - "Beoordelen nieuwe registraties": "assess-new-registrations.md"
    - "Registraties vinden": "filter-registrations.md"
    - "Registraties bewerken": "edit-registration.md"
    - "Print een Papieren Voucher": "print-paper-voucher.md"
    - "Betalingen Pauzeren": "pause-payments.md"
    - "Betalingen Beeindigen": "end-payments.md"
    - "Toegang": "access.md"
