# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# And: https://squidfunk.github.io/mkdocs-material/publishing-your-site/

name: 'Deploy: Azure Static Web App'

on:
  workflow_dispatch:
  push:
    branches:
      - new
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - new

permissions:
  contents: read
  deployments: write
  pull-requests: write # Enable preview-link comments

jobs:
  build:
    environment: new
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build EN
        working-directory: config/en
        run: |
          mkdocs build

      - name: Build NL
        working-directory: config/nl
        run: |
          mkdocs build

      - name: 'Create redirect `/`'
        run: |-
          cat <<EOF > www/index.html
          <!doctype html>
          <title>Redirecting...</title>
          <meta http-equiv="refresh" content="1;url=/en/">
          EOF

      # More information on Static Web App workflow configurations,
      # See: https://aka.ms/swaworkflowconfig
      - name: Deploy to Azure Static Web App
        id: deployment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANUAL }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          config_file_location: '/'
          app_location: 'www'
          output_location: ''
          skip_app_build: true

      - name: Finish
        run: |
          echo "Deployed at: ${{ steps.deployment.outputs.static_web_app_url }}" >> $GITHUB_STEP_SUMMARY

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request
    environment: new
    steps:
      - name: 'Clean up preview-build'
        uses: Azure/static-web-apps-deploy@v1
        env:
          SKIP_DEPLOY_ON_MISSING_SECRETS: true
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANUAL }}
          action: 'close'
          app_location: 'www'
