# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Test: Markdown Syntax'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - new
    paths:
      - '.github/workflows/test_markdown-syntax.yml'
      - '**/*.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Run Markdownlint'
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          config: '.markdownlint.yml'
          globs: '**/*.md'
